# Generated by Django 5.0.4 on 2024-04-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("semlor", "0002_import_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semlor",
            name="picture",
            field=models.ImageField(blank=True, upload_to="semlor_pictures/"),
        ),
    ]
