name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      git_hash:
        description: 'Git hash to use for the image'
        required: true

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-central-1

      - name: Update ECS service with new task definition
        run: |
          aws ecs update-service --cluster semlor-cluster --service semlor --force-new-deployment --task-definition semlor:${{ github.event.inputs.git_hash }}
          aws ecs update-service --cluster semlor-cluster --service semlor-nginx --force-new-deployment --task-definition semlor-nginx:${{ github.event.inputs.git_hash }}
