name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 and Black
        run: |
          flake8 soruce
          black --check source

      - name: Run Tests
        run: python manage.py test semlor

      - name: Build App Docker Image
        run: |
          docker build -t semlor .

      - name: Build Nginx Docker Image
        run: |
          cd nginx
          docker build -t semlor-nginx .

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-central-1

      - name: Tag and Push App Docker Image to AWS ECR
        run: |
          docker tag semlor:latest aws_account_id.dkr.ecr.aws_region.amazonaws.com/semlor:${GITHUB_SHA::8}
          docker push 058264290495.dkr.ecr.eu-central-1.amazonaws.com/semlor:${GITHUB_SHA::8}

      - name: Tag and Push Nginx Docker Image to AWS ECR
        run: |
          docker tag semlor-nginx:latest aws_account_id.dkr.ecr.aws_region.amazonaws.com/semlor-nginx:${GITHUB_SHA::8}
          docker push 058264290495.dkr.ecr.aws_region.amazonaws.com/semlor-nginx:${GITHUB_SHA::8}
